Add support for ewc jh
energywebfoundation/ens-app-v3 pull request #4
Opened 2023-09-05 13:21 UTC by JGiter

2023-09-05 15:02 UTC, jrhender approved these changes

2023-09-05 15:03 UTC, jrhender requested changes
Actually I think better to not merge this PR

2023-09-05 15:07 UTC, jrhender commented
@JGiter my thinking is that is better to have a branch that we deploy from and keep `main` in lock-step with the `main` branch from the upstream repo (at https://github.com/ensdomains/ens-app-v3). How does this sound to you?

2023-09-06 05:41 UTC, JGiter commented
> keep main in lock-step with the main branch from the upstream

We can do that, but this is not really necessary. Usually working with fork doesn't forbid changing it. We just need to [synchronize](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) from time to time with PR when conflicts appears

2023-09-06 12:45 UTC, jrhender approved these changes

2023-09-06 12:53 UTC, merged